export const SAY_HELLO_TO_OFFERS = [
  {
    id: 'c12',
    path: `${process.env.PUBLIC_URL}/product`,
    image: 'assets/images/product/8.png',
    title: 'Assorted Capsicum Combo',
    qty: 615,
    price: 22.25,
    amount: 0,
    disc: 15,
  },
  {
    id: 'c13',
    path: `${process.env.PUBLIC_URL}/product`,
    image: 'assets/images/product/6.png',
    title: 'Assorted Capsicum Combo',
    qty: 620,
    price: 23.15,
    amount: 0,
    disc: 25,
  },
  {
    id: 'c14',
    path: `${process.env.PUBLIC_URL}/product`,
    image: 'assets/images/product/7.png',
    title: 'Assorted Capsicum Combo',
    qty: 550,
    amount: 0,
    price: 32.25,
    disc: 15,
  },
];
