export const ORDER_LIST = [
  {
    path: `${process.env.PUBLIC_URL}/order-detail`,
    path2: `${process.env.PUBLIC_URL}/delivery-address`,
    id: 'ID: #5151515 ',
    date: 'Dt: 20 Dec, 2020',
    address: '8857 Morris Rd. ,Charlottesville',
    price: '$250.00',
    qty: 15,
    image: 'assets/images/map/map.jpg',
    alt: 'map',
    rating: 2,
  },
  {
    path: `${process.env.PUBLIC_URL}/order-detail`,
    path2: `${process.env.PUBLIC_URL}/delivery-address`,
    id: 'ID: #5151515 ',
    date: 'Dt: 20 Dec, 2020',
    address: '8857 Morris Rd. ,Charlottesville',
    price: '$250.00',
    qty: 15,
    image: 'assets/images/map/map.jpg',
    alt: 'map',
    rating: 3,
  },
  {
    path: `${process.env.PUBLIC_URL}/order-detail`,
    path2: `${process.env.PUBLIC_URL}/delivery-address`,
    id: 'ID: #5151515 ',
    date: 'Dt: 20 Dec, 2020',
    address: '8857 Morris Rd. ,Charlottesville',
    price: '$250.00',
    qty: 15,
    image: 'assets/images/map/map.jpg',
    alt: 'map',
    rating: 1,
  },
  {
    path: `${process.env.PUBLIC_URL}/order-detail`,
    path2: `${process.env.PUBLIC_URL}/delivery-address`,
    id: 'ID: #5151515 ',
    date: 'Dt: 20 Dec, 2020',
    address: '8857 Morris Rd. ,Charlottesville',
    price: '$250.00',
    qty: 15,
    image: 'assets/images/map/map.jpg',
    alt: 'map',
    rating: 5,
  },
];
